/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_fibservice_FibLib */

#ifndef _Included_com_example_fibservice_FibLib
#define _Included_com_example_fibservice_FibLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_fibservice_FibLib
 * Method:    fib
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_example_fibservice_FibLib_fib
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
